package example.db;


import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.Base64;
import java.util.Properties;


public class DatabaseConnection {

    private static final Properties P = new Properties();

    static {
        try {
            Class.forName("org.hsqldb.jdbc.JDBCDriver");
        } catch (ClassNotFoundException e) {
            throw new RuntimeException(e);
        }

        try (InputStream is = DatabaseConnection.class.getClassLoader().getResourceAsStream("db.properties")) {
            if (is == null) throw new RuntimeException("db.properties not found in classpath");
            P.load(is);
        } catch (Exception e) {
            throw new RuntimeException("Failed to load db.properties", e);
        }
    }

    public static Connection getConnection() throws SQLException {
        String url = P.getProperty("db.url");
        String user = P.getProperty("db.user");
        String passB64 = P.getProperty("db.pass.b64", "");
        String pass = new String(Base64.getDecoder().decode(passB64), StandardCharsets.UTF_8);
        return DriverManager.getConnection(url, user, pass);
    }

    public static void initSchema() {
        String ddl =
                "CREATE TABLE IF NOT EXISTS results (" +
                        "    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                        "    hit INTEGER," +
                        "    x DOUBLE," +
                        "    y DOUBLE," +
                        "    r DOUBLE," +
                        "    ses VARCHAR(128)" +
                        ");";

        try (Connection conn = getConnection();
             java.sql.Statement st = conn.createStatement()) {
            st.executeUpdate(ddl);
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

}